# Generated by Django 3.1.5 on 2021-03-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg_api', '0002_auto_20210315_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexlivre',
            name='author',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='indexlivre',
            name='coverBook',
            field=models.CharField(default='', max_length=255),
        ),
    ]
