# Generated by Django 3.1.7 on 2021-03-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg_api', '0003_auto_20210315_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexLivre',
            new_name='BookModel',
        ),
    ]
