# Generated by Django 3.1.7 on 2021-03-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg_api', '0004_auto_20210326_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookIndexModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(default='', max_length=150)),
                ('occurence', models.CharField(default='', max_length=5)),
                ('idBook', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
    ]
