# Generated by Django 3.1.7 on 2021-04-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg_api', '0006_auto_20210406_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphjaccard',
            options={'ordering': ('bookSrc', 'bookDes')},
        ),
        migrations.AddField(
            model_name='graphjaccard',
            name='id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='coverBook',
            field=models.CharField(default='', max_length=355),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='graphjaccard',
            name='bookSrc',
            field=models.IntegerField(default='-1'),
        ),
    ]
