# Generated by Django 3.1.7 on 2021-04-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg_api', '0007_auto_20210406_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='crank',
            field=models.IntegerField(null=True),
        ),
    ]
