# Generated by Django 3.1.7 on 2021-04-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gutenberg_api', '0008_bookmodel_crank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='crank',
            field=models.FloatField(default='0.0'),
        ),
    ]
